'use client'

import { useState } from 'react'
import { Copy, Check, ChevronDown, Menu, ShieldCheck, Wallet, X, Users, BriefcaseBusiness } from 'lucide-react'
const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_00000000373c82109a6af192f4de48b4-P7zBMGdjXg1WFpoOC5AfztrRudjvYL.png'
const treasuryWallets = [
  { chain: 'BSC', asset: 'USDT', address: '0xc240766472FEd8bB8fdf39c9362bAbbE7e3086A1' },
  { chain: 'Ethereum', asset: 'USDT / ETH', address: '0xc240766472FEd8bB8fdf39c9362bAbbE7e3086A1' },
  { chain: 'Solana', asset: 'SOL', address: 'AVmgiG5hK6YfCufjC671gyZZVjZ23AJLnxdkjuj58yZi' },
  { chain: 'Bitcoin', asset: 'BTC', address: 'bc1pd8k2d9dljvwfy5nadl9vhzl8ke2k007hfzeale0fwvxgzmtav45sleqex8' },
  { chain: 'TRON', asset: 'USDT', address: 'TRHsaAu4f1gfvEVFmu4YDDmk3ZLTv7guvC' },
]
const supportTiers = [
  ['Gold', '🥇', '$100 to $999'], ['Silver', '🥈', '$1000 to $10,000'], ['Diamond', '💎', '$10,000 to $100,000'], ['SHARK', '🦈', 'UNLIMITED'],
]
const leadership = [
  ['FOUNDER / CEO', 'Vision, strategy, and overall leadership'], ['CO-FOUNDER / COO', 'Operations and business execution'], ['CFO', 'Financial management and investment strategy'], ['CTO', 'Technology and infrastructure'], ['CMO', 'Marketing and growth'], ['Chief Investment Officer (CIO)', 'Investment decisions and portfolio management'], ['Head of Business Development', 'Partnerships and expansion'],
]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [dialog, setDialog] = useState<'support' | 'wallet' | null>(null)
  const [copied, setCopied] = useState<string | null>(null)
  const [connected, setConnected] = useState<string | null>(null)
  const [walletError, setWalletError] = useState<string | null>(null)

  const copyAddress = async (chain: string, address: string) => {
    await navigator.clipboard?.writeText(address)
    setCopied(chain)
    window.setTimeout(() => setCopied(null), 1600)
  }
  const connectWallet = async (chain: 'Ethereum' | 'Solana' | 'TRON' | 'Bitcoin') => {
    setWalletError(null)
    try {
      const browser = window as Window & { ethereum?: { request: (a: { method: string }) => Promise<string[]> }; solana?: { connect: () => Promise<{ publicKey: { toString: () => string } }> }; tronLink?: { request: (a: { method: string }) => Promise<string[]> }; unisat?: { requestAccounts: () => Promise<string[]> } }
      let address = ''
      if (chain === 'Ethereum') { if (!browser.ethereum) throw new Error('Install MetaMask or another Ethereum wallet to continue.'); address = (await browser.ethereum.request({ method: 'eth_requestAccounts' }))[0] }
      if (chain === 'Solana') { if (!browser.solana) throw new Error('Install Phantom or another Solana wallet to continue.'); address = (await browser.solana.connect()).publicKey.toString() }
      if (chain === 'TRON') { if (!browser.tronLink) throw new Error('Install TronLink to continue.'); address = (await browser.tronLink.request({ method: 'tron_requestAccounts' }))[0] }
      if (chain === 'Bitcoin') { if (!browser.unisat) throw new Error('Install UniSat or another Bitcoin wallet to continue.'); address = (await browser.unisat.requestAccounts())[0] }
      setConnected(`${chain}: ${address}`)
    } catch (error) { setWalletError(error instanceof Error ? error.message : 'Wallet connection was cancelled.') }
  }

  return (
    <main className="min-h-screen overflow-hidden bg-[#050a19] text-slate-100">
      <div className="pointer-events-none fixed inset-0 -z-0 bg-[radial-gradient(circle_at_70%_8%,rgba(20,79,199,.22),transparent_35%),radial-gradient(circle_at_15%_40%,rgba(246,176,26,.08),transparent_28%)]" />
      <header className="relative z-20 border-b border-white/[.08] bg-[#050a19]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3"><img src={logoUrl} alt="SharkPay logo" className="size-11 object-contain" /><div><p className="font-semibold tracking-[.2em]">SHARKPAY</p><p className="text-[9px] tracking-[.28em] text-[#f4ba37]">FAST · SECURE · GLOBAL</p></div></a><nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#support">Support tiers</a><a href="#leadership">Leadership</a><a href="#deposit">Deposit</a></nav><button onClick={() => setDialog('wallet')} className="hidden rounded-full bg-[#f4b82e] px-5 py-2.5 text-sm font-semibold text-[#071126] md:block">Connect wallet <Wallet className="ml-1 inline size-4" /></button><button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="flex flex-col gap-4 border-t border-white/[.08] px-5 py-5 text-sm md:hidden"><a href="#support" onClick={() => setMenuOpen(false)}>Support tiers</a><a href="#leadership" onClick={() => setMenuOpen(false)}>Leadership</a><a href="#deposit" onClick={() => setMenuOpen(false)}>Deposit</a></nav>}</header>

      <section id="top" className="relative z-10 mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-24"><div><p className="mb-7 inline-flex rounded-full border border-[#f4b82e]/30 bg-[#f4b82e]/[.08] px-3.5 py-2 text-xs font-medium text-[#fbd77a]">Digital asset investing, made clear</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-6xl lg:text-7xl">Put your crypto to <span className="bg-gradient-to-r from-[#ffe39a] via-[#f4b82e] to-[#df8a13] bg-clip-text text-transparent">work.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">A more thoughtful way to grow your digital assets. Choose your support tier, connect securely, and keep your portfolio working around the clock.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#support" className="rounded-full bg-[#f4b82e] px-6 py-3.5 text-center font-semibold text-[#071126]">Explore support tiers</a><button onClick={() => setDialog('wallet')} className="rounded-full border border-white/15 px-6 py-3.5 font-medium">Connect wallet <Wallet className="ml-1 inline size-4" /></button></div></div><div className="relative overflow-hidden rounded-[2rem] border border-[#f4b82e]/20 bg-[#091631] shadow-[0_25px_100px_rgba(0,55,180,.25)]"><img src="/sharkpay-support.png" alt="Shark emerging from deep blue water" className="h-[330px] w-full object-cover" /><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/10 bg-[#071126]/85 p-4 backdrop-blur"><p className="text-xs uppercase tracking-[.2em] text-[#f4b82e]">Investor support</p><p className="mt-1 text-lg font-semibold">Built for every level of conviction.</p></div></div></section>

      <section id="support" className="relative z-10 border-y border-white/[.07] bg-[#08132a]/70 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.22em] text-[#f4b82e]">SHARKYPAY SUPPORT</p><h2 className="text-3xl font-semibold sm:text-4xl">Choose your level of support.</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">Tap any tier to review the support level and connect a wallet when you are ready.</p></div><button onClick={() => setDialog('support')} className="group relative min-h-48 w-full overflow-hidden rounded-3xl border border-[#f4b82e]/40 bg-gradient-to-r from-[#172c4d] to-[#0b1933] p-7 text-left shadow-[0_12px_45px_rgba(244,184,46,.08)]"><img src="/sharkpay-support.png" alt="" className="absolute inset-0 size-full object-cover opacity-30 transition duration-500 group-hover:scale-105" /><div className="relative"><p className="text-2xl font-semibold text-white">SHARKYPAY SUPPORT</p><p className="mt-2 max-w-md text-slate-300">Open the support tiers and find the right fit for your investment journey.</p><span className="mt-6 inline-flex rounded-full bg-[#f4b82e] px-5 py-2.5 text-sm font-semibold text-[#071126]">View support tiers <ChevronDown className="ml-2 size-4" /></span></div></button></div></section>

      <section id="leadership" className="relative z-10 mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-10"><p className="mb-3 text-xs font-semibold uppercase tracking-[.22em] text-[#f4b82e]">Our people</p><h2 className="text-3xl font-semibold sm:text-4xl">LEADERSHIP &amp; MANAGEMENT</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{leadership.map(([role, description]) => <article key={role} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="mb-5 flex size-10 items-center justify-center rounded-xl bg-[#f4b82e]/10 text-[#f4b82e]"><BriefcaseBusiness className="size-5" /></div><h3 className="font-semibold text-white">{role}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p></article>)}</div></section>

      <section id="deposit" className="relative z-10 border-t border-white/[.07] bg-[#071127] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.22em] text-[#f4b82e]">Secure deposit</p><h2 className="text-3xl font-semibold sm:text-4xl">Supported chains</h2></div><div className="flex items-center gap-2 text-sm text-slate-400"><ShieldCheck className="size-4 text-[#f4b82e]" /> Addresses are hidden. Copy only.</div></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{treasuryWallets.map((wallet) => <div key={wallet.chain} className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-4"><div><p className="font-semibold text-white">{wallet.chain}</p><p className="mt-1 text-xs text-slate-500">{wallet.asset} · Treasury address hidden</p></div><button onClick={() => copyAddress(wallet.chain, wallet.address)} className="inline-flex shrink-0 items-center gap-2 rounded-full border border-[#f4b82e]/40 px-3 py-2 text-xs font-semibold text-[#fbd77a]">{copied === wallet.chain ? <Check className="size-4" /> : <Copy className="size-4" />} {copied === wallet.chain ? 'Copied' : 'Copy address'}</button></div>)}</div><button onClick={() => setDialog('wallet')} className="mt-8 rounded-full bg-[#f4b82e] px-6 py-3.5 font-semibold text-[#071126]">Connect wallet <Wallet className="ml-1 inline size-4" /></button></div></section>

      <footer className="relative z-10 border-t border-white/[.07] px-5 py-8 lg:px-8"><div className="mx-auto max-w-7xl text-xs text-slate-500">© 2026 SharkPay. Digital asset services for informed investors.</div></footer>

      {dialog && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020611]/80 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl border border-[#f4b82e]/25 bg-[#0b1933] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#f4b82e]">SharkPay</p><h2 id="dialog-title" className="mt-2 text-2xl font-semibold">{dialog === 'support' ? 'SHARKYPAY SUPPORT' : 'Connect wallet'}</h2></div><button onClick={() => setDialog(null)} className="rounded-full p-2 text-slate-400 hover:bg-white/10" aria-label="Close dialog"><X className="size-5" /></button></div>{dialog === 'support' ? <div className="mt-6 grid gap-3">{supportTiers.map(([name, icon, range]) => <div key={name} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex items-center gap-3"><span className="text-2xl">{icon}</span><div><p className="font-semibold text-white">{name}</p><p className="text-sm text-slate-400">{range}</p></div></div>{name === 'SHARK' && <p className="mt-3 text-xs font-medium text-[#fbd77a]">INVESTOR MUST BE VERIFIED</p>}</div>)}</div> : <div className="mt-6"><div className="grid gap-3 sm:grid-cols-2">{(['Ethereum', 'Solana', 'TRON', 'Bitcoin'] as const).map((chain) => <button key={chain} onClick={() => connectWallet(chain)} className="rounded-2xl border border-white/10 bg-[#071126] p-4 text-left hover:border-[#f4b82e]/50"><p className="font-semibold text-white">{chain}</p><p className="mt-1 text-xs text-slate-500">Connect compatible wallet</p></button>)}</div>{connected && <p className="mt-5 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-300">Connected: {connected}</p>}{walletError && <p className="mt-5 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-300">{walletError}</p>}</div>}</div></div>}
    </main>
  )
}
