'use client'

import { useState, type ReactNode } from 'react'
import { ArrowRight, BarChart3, Check, Globe2, Headphones, LockKeyhole, Menu, Play, ShieldCheck, TrendingUp, Users, Wallet, X } from 'lucide-react'

const plans = [
  ['Gold', '🥇', '$100 – $999', 'Entry-level access for investors beginning their digital asset journey.'],
  ['Silver', '🥈', '$1,000 – $10,000', 'A higher-capacity tier for increasing portfolio exposure.'],
  ['Diamond', '💎', '$10,000 – $100,000', 'Premium allocation for high-value investors.', 'ELITE INVESTOR'],
  ['SHARK', '🦈', 'UNLIMITED', 'Unlimited capacity subject to verification and applicable requirements.', 'VERIFIED INVESTORS ONLY'],
]
const leadership = ['FOUNDER / CEO', 'CO-FOUNDER / COO', 'CFO', 'CTO', 'CMO', 'CHIEF INVESTMENT OFFICER (CIO)', 'HEAD OF BUSINESS DEVELOPMENT']
const assets = ['Bitcoin', 'Ethereum', 'BNB', 'USDT', 'USDC', 'Solana']

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [modal, setModal] = useState<string | null>(null)
  return <main className="min-h-screen bg-[#030914] text-white">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#030914]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#home" className="flex items-center gap-3"><img src="/sharkpay-logo.png" alt="SHARKYPAY logo" className="size-11 rounded-full object-cover" /><span><b className="block tracking-[.22em]">SHARKYPAY</b><small className="text-[9px] tracking-[.25em] text-slate-500">DIGITAL ASSET PLATFORM</small></span></a><nav className="hidden gap-7 text-sm text-slate-300 lg:flex"><a href="#about">About</a><a href="#plans">Investment Plans</a><a href="#how">How It Works</a><a href="#leadership">Leadership</a><a href="#security">Security</a><a href="#contact">Contact</a></nav><div className="hidden gap-3 md:flex"><a href="#login" className="rounded-full border border-white/15 px-5 py-2.5 text-sm">Login</a><a href="#plans" className="rounded-full bg-[#64f6a5] px-5 py-2.5 text-sm font-bold text-[#03151a]">Get Started</a></div><button onClick={() => setMenu(!menu)} className="rounded-lg p-2 lg:hidden" aria-label="Toggle navigation">{menu ? <X /> : <Menu />}</button></div>{menu && <nav className="flex flex-col gap-5 border-t border-white/10 px-5 py-5 text-sm lg:hidden"><a href="#about">About</a><a href="#plans">Investment Plans</a><a href="#how">How It Works</a><a href="#leadership">Leadership</a><a href="#security">Security</a></nav>}</header>
    <section id="home" className="relative mx-auto grid max-w-7xl items-center gap-12 overflow-hidden px-5 pb-20 pt-20 lg:grid-cols-2 lg:px-8 lg:pb-28"><div><Label>BUILD WEALTH IN A DIGITAL FUTURE</Label><h1 className="text-5xl font-semibold leading-[1.03] tracking-[-.055em] sm:text-6xl">Smart Crypto Investments for a <span className="bg-gradient-to-r from-[#64f6a5] to-[#25c8f5] bg-clip-text text-transparent">Brighter Tomorrow</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">SHARKYPAY provides a modern digital asset investment experience designed to help users manage and grow their crypto portfolios.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#plans" className="rounded-full bg-[#64f6a5] px-6 py-3.5 text-center font-bold text-[#03151a]">Start Investing <ArrowRight className="ml-1 inline size-4" /></a><button className="rounded-full border border-[#64f6a5]/60 px-6 py-3.5 font-semibold"><Play className="mr-2 inline size-4 fill-current" /> Watch Demo</button></div></div><div className="rounded-[2rem] border border-[#2dbbff]/35 bg-gradient-to-br from-[#0a1d3a] to-[#061022] p-6 shadow-[0_30px_100px_rgba(0,114,255,.22)]"><div className="flex justify-between border-b border-white/10 pb-4 text-sm"><span className="text-slate-400">Portfolio overview</span><span className="text-[#64f6a5]">Live preview</span></div><p className="mt-8 text-sm text-slate-500">Total balance</p><p className="text-4xl font-bold">$24,680.50</p><p className="text-sm text-[#64f6a5]">↗ +8.35% this month</p><div className="mt-8 flex h-48 items-end gap-2 rounded-2xl bg-[#071630] p-5">{[22,35,28,52,45,64,58,78,71,92].map((height, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-[#1689ff] to-[#64f6a5]" style={{ height: `${height}%` }} />)}</div><div className="mt-4 grid grid-cols-3 gap-3">{['BTC', 'ETH', 'BNB'].map((item) => <div key={item} className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-center"><span className="text-[#64f6a5]">●</span><p className="mt-2 text-xs">{item}</p><small className="text-[#64f6a5]">+2.4%</small></div>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl grid-cols-2 gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 px-5 lg:grid-cols-4 lg:px-8">{[['50K+', 'Active Users', Users], ['$120M+', 'Assets Managed', Wallet], ['99.9%', 'Platform Uptime', ShieldCheck], ['180+', 'Markets Supported', Globe2]].map(([value, label, Icon]) => <div key={String(label)} className="bg-[#071426] p-6"><Icon className="mb-3 text-[#64f6a5]" /><b className="block text-2xl">{String(value)}</b><small className="text-slate-500">{String(label)}</small></div>)}</section>
    <section id="about" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><Label>WHY SHARKYPAY</Label><h2 className="text-4xl font-semibold">Built for the future of digital finance.</h2></div><div><p className="text-lg leading-8 text-slate-400">SHARKYPAY is a modern digital asset investment and financial technology platform designed to make portfolio management feel clear, connected and considered.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><Feature icon={<LockKeyhole />} title="Secure Investments" text="Modern security features designed to help protect your account and digital assets." /><Feature icon={<TrendingUp />} title="Smart Portfolio" text="Monitor digital assets and investment performance from one dashboard." /><Feature icon={<BarChart3 />} title="Multiple Assets" text="Access BTC, ETH, BNB and stablecoins in one place." /><Feature icon={<Headphones />} title="24/7 Support" text="Get assistance whenever you need help with your account." /></div></div></div></section>
    <section id="plans" className="border-y border-white/[.07] bg-[#071426]/70 px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><Label>INVESTMENT PLANS</Label><h2 className="text-4xl font-semibold">A plan for every ambition.</h2><div className="mt-10 grid gap-5 lg:grid-cols-4">{plans.map(([name, mark, range, description, badge]) => <article key={name} className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><span className="text-3xl">{mark}</span>{badge && <span className="float-right rounded-full bg-[#64f6a5]/10 px-2 py-1 text-[9px] text-[#64f6a5]">{badge}</span>}<h3 className="mt-5 text-xl font-semibold">{name}</h3><p className="mt-2 text-2xl font-bold text-[#64f6a5]">{range}</p><p className="mt-4 min-h-16 text-sm leading-6 text-slate-400">{description}</p><ul className="mt-5 flex flex-col gap-3 border-t border-white/10 pt-5 text-sm text-slate-300">{['Portfolio monitoring', 'Investment dashboard', 'Transaction history', 'Account support'].map((item) => <li key={item}><Check className="mr-2 inline size-4 text-[#64f6a5]" />{item}</li>)}</ul><button onClick={() => setModal(name)} className="mt-7 w-full rounded-full border border-[#64f6a5]/50 px-4 py-3 text-sm font-semibold hover:bg-[#64f6a5] hover:text-[#03151a]">{name === 'SHARK' ? 'Apply for SHARK Access' : `Invest in ${name}`}</button></article>)}</div><p className="mt-8 text-center text-xs text-slate-500">Investment availability, limits, and eligibility may be subject to verification, applicable terms, and regulatory requirements. Digital asset investments involve risk.</p></div></section>
    <section id="how" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Label>HOW IT WORKS</Label><h2 className="text-4xl font-semibold">Simple steps. Clear visibility.</h2><div className="mt-10 grid gap-6 md:grid-cols-4">{[['01', 'CREATE ACCOUNT'], ['02', 'FUND ACCOUNT'], ['03', 'CHOOSE INVESTMENT'], ['04', 'MONITOR PORTFOLIO']].map(([number, title]) => <div key={number} className="border-t border-[#64f6a5]/50 pt-5"><span className="text-[#64f6a5]">{number}</span><h3 className="mt-7 font-semibold">{title}</h3><p className="mt-3 text-sm text-slate-500">A secure, transparent step in your investment journey.</p></div>)}</div></section>
    <section className="border-y border-white/[.07] bg-[#071426]/60 px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><Label>MARKET WATCH</Label><h2 className="text-4xl font-semibold">Supported digital assets.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{assets.map((asset, i) => <div key={asset} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] p-4"><span><b>{asset}</b><small className="ml-2 text-slate-500">{['BTC', 'ETH', 'BNB', 'USDT', 'USDC', 'SOL'][i]}</small></span><span className="text-right">$1,000.00<br /><small className="text-[#64f6a5]">+2.4%</small></span></div>)}</div></div></section>
    <section id="leadership" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Label>OUR PEOPLE</Label><h2 className="text-4xl font-semibold">LEADERSHIP &amp; MANAGEMENT</h2><p className="mt-4 text-slate-400">Experienced leadership driving SHARKYPAY&apos;s vision, technology, investment strategy and global growth.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{leadership.map((role, i) => <article key={role} className="rounded-2xl border border-white/10 bg-white/[.035] p-5 hover:border-[#64f6a5]/50"><div className="grid size-12 place-items-center rounded-full bg-[#64f6a5]/10 text-[#64f6a5]">{String(i + 1).padStart(2, '0')}</div><h3 className="mt-5 text-sm font-semibold">{role}</h3><p className="mt-3 text-sm leading-6 text-slate-500">Professional profile information will be published when supplied by the SHARKYPAY team.</p></article>)}</div></section>
    <section id="security" className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-3xl border border-[#2dbbff]/25 bg-gradient-to-br from-[#0a203b] to-[#071224] p-8 sm:p-12"><Label>SECURITY COMES FIRST</Label><h2 className="text-4xl font-semibold">Built with protection in mind.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Secure authentication', 'Two-factor authentication', 'Account protection', 'Transaction monitoring', 'Withdrawal protection', 'Data encryption', 'Security notifications', 'Risk management'].map((item) => <div key={item} className="rounded-xl border border-white/10 bg-white/[.04] p-4 text-sm"><ShieldCheck className="mb-3 text-[#64f6a5]" />{item}</div>)}</div></div></section>
    <section id="contact" className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-3xl border border-[#64f6a5]/30 bg-gradient-to-r from-[#0a302a] to-[#0a1c38] p-8 sm:p-14"><Label>START TODAY</Label><h2 className="max-w-2xl text-4xl font-semibold">Start your digital asset journey with SHARKYPAY.</h2><p className="mt-4 text-slate-400">Experience a modern platform designed for managing and investing in digital assets.</p><a href="#plans" className="mt-8 inline-block rounded-full bg-[#64f6a5] px-6 py-3.5 font-bold text-[#03151a]">Explore Investment Plans</a></div></section>
    <section id="license" className="px-5 pb-24 lg:px-8"><div className="mx-auto grid max-w-7xl items-start gap-10 rounded-3xl border border-[#f4c95d]/30 bg-gradient-to-br from-[#171b2d] to-[#081226] p-8 sm:p-12 lg:grid-cols-[.72fr_1.28fr]"><div className="lg:sticky lg:top-28"><Label>COMPANY DOCUMENTATION</Label><h2 className="text-4xl font-semibold">SHARKYPAY company records.</h2><p className="mt-4 text-slate-400">The document shown here is a Certificate of Dissolution for ShakePay Limited. It is not a SHARKYPAY license, and it must not be presented as proof that SHARKYPAY is licensed, active, or regulated.</p><div className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm leading-6 text-amber-100/75"><b className="text-amber-200">Important verification notice</b><br />Always verify company status, registration, and regulatory permissions directly with the relevant official authority before investing.</div></div><figure className="overflow-hidden rounded-2xl border border-white/15 bg-white p-2 shadow-2xl"><img src="/company-dissolution-certificate.png" alt="Certificate of Dissolution of a Private Limited Company for ShakePay Limited" className="h-auto w-full" /><figcaption className="bg-[#080f1d] px-4 py-3 text-center text-xs leading-5 text-slate-400">Reference document provided by the user. This document identifies ShakePay Limited and records dissolution on 13 August 2019; it does not establish SHARKYPAY licensing.</figcaption></figure></div></section>
    <footer className="border-t border-white/10 px-5 py-10 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row"><div><b className="tracking-[.22em]">SHARKYPAY</b><p className="mt-3 text-sm text-slate-500">Modern digital asset investment infrastructure for informed investors.</p></div><div className="grid grid-cols-2 gap-4 text-sm text-slate-400"><a href="#about">About</a><a href="#plans">Investment Plans</a><a href="#security">Security</a><a href="#contact">Contact</a><a href="#terms">Terms</a><a href="#privacy">Privacy</a></div></div><p className="mx-auto mt-8 max-w-7xl border-t border-white/10 pt-5 text-xs text-slate-600">© 2026 SHARKYPAY. All rights reserved. Digital asset investments involve risk.</p></footer>
    {modal && <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-3xl border border-[#64f6a5]/30 bg-[#091a2d] p-6"><div className="flex justify-between"><div><Label>{modal === 'SHARK' ? 'INVESTOR VERIFICATION' : 'INVESTMENT FLOW'}</Label><h2 className="text-2xl font-semibold">{modal === 'SHARK' ? 'SHARK access application' : `Invest in ${modal}`}</h2></div><button onClick={() => setModal(null)} aria-label="Close"><X /></button></div><form className="mt-6 flex flex-col gap-4" onSubmit={(e) => { e.preventDefault(); setModal(null) }}><input required placeholder="Full name" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3" /><input required type="email" placeholder="Email address" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3" /><input required placeholder={modal === 'SHARK' ? 'Country and source of funds' : 'Investment amount'} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3" /><p className="text-xs text-slate-500">Frontend flow only. Real transactions require a connected backend and verified service.</p><button className="rounded-full bg-[#64f6a5] px-5 py-3 font-bold text-[#03151a]" type="submit">{modal === 'SHARK' ? 'Submit for review' : 'Continue securely'} <ArrowRight className="ml-1 inline size-4" /></button></form></div></div>}
  </main>
}

function Label({ children }: { children: ReactNode }) { return <p className="mb-4 text-xs font-semibold uppercase tracking-[.24em] text-[#64f6a5]">{children}</p> }
function Feature({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-5 hover:-translate-y-1 hover:border-[#64f6a5]/50"><span className="mb-5 grid size-11 place-items-center rounded-xl bg-gradient-to-br from-[#64f6a5] to-[#1eb5ff] text-[#03151a]">{icon}</span><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article> }
function Stat({ icon, value, label }: { icon: ReactNode; value: string; label: string }) { return <div><span>{icon}</span><b>{value}</b><small>{label}</small></div> }
